version: '3'
services:
  author:
    image: aem-author
    build: ./aem-author
    ports:
      - "4502:4502"
  publisher:
    image: aem-publisher
    build: ./aem-publisher
    ports:
      - "4503:4503"
  dispatcher:
    image: aem-dispatcher
    build: ./aem-dispatcher
    ports:
      - "80:80"
    depends_on:
      - "publisher"